# pole star db proxy config file

# 工作机器ID（用于雪花ID生成器）
workId = 1
# 业务ID号（用于雪花ID生成器）
businessId =2

# 日志配置
[log]
logPath = "/tmp/polestar_dbproxy.log"
logLevel = "debug"

[rpcServer]
addr = "0.0.0.0:10048"

[[mysql.masters]]
# 主数据库(读写)
name = "master01"
dsn = "mysql://root:123456@127.0.0.1:3306/polestar?charset=utf8mb4"
active = 100
idle = 2

[[mysql.slaves]]
# 备份数据库(只读)
name = "slave01"
dsn = "mysql://root:123456@127.0.0.1:3306/polestar?charset=utf8mb4&slave=true"
active = 100
idle = 2

[queue]
# 默认协程数(最好小于等于mysql最大连接数)
routines = 100
# 默认超时（秒）
timeout = 5
# 默认容量
cap=50
# 输出调试队列数据
debug = true

[redis]
# redis auth password
password = ""
# redis db index (0~15)
index = 0
# redis master host
masterHost = "127.0.0.1:6379"
# redis replicate hosts
replicateHosts = []
# default connect timeout (ms)
connTimeout = 1000
# default connect timeout (ms)
readTimeout = 1000
# default connect timeout (ms)
writeTimeout = 1000
# default keep alive 30s
keepAlive = 30
# default alive time 60s
aliveTime = 60