# pole star app server config file

# 工作机器ID（用于雪花ID生成器）
workId = 1
# 业务ID号（用于雪花ID生成器）
businessId =1
# 日志配置
[log]
logPath = "/tmp/polestar_server.log"
logLevel = "debug"

[settings]
addr = "wss://127.0.0.1:8080"

[redis]
# redis auth password
password = ""
# redis db index (0~15)
index = 0
# redis master host
masterHost = "127.0.0.1:6379"
# redis replicate hosts
replicateHosts = []
# default connect timeout (ms)
connTimeout = 1000
# default connect timeout (ms)
readTimeout = 1000
# default connect timeout (ms)
writeTimeout = 1000
# default keep alive 30s
keepAlive = 30
# default alive time 60s
aliveTime = 60